"""add ai_questions

Revision ID: 78c7cd6d0808
Revises: d49516e0cc77
Create Date: 2026-01-06 06:01:15.605870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c7cd6d0808'
down_revision = 'd49516e0cc77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('qtype', sa.String(length=30), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('choices_json', sa.Text(), nullable=True),
    sa.Column('answer', sa.String(length=300), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_questions')
    # ### end Alembic commands ###
